FROM ruby:latest

RUN apt-get update -y && \
    apt-get install -y \
    lsof \
    build-essential \
    libpq-dev \
    nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV TERM xterm-256color

RUN gem install bundler

WORKDIR /var/www

COPY srcs/auth/authentication /var/www/authentication

WORKDIR /var/www/authentication

RUN bundle install

COPY srcs/auth/ /var/www/

EXPOSE 9292

CMD ["bundle", "exec", "ruby", "server.rb"]