FROM ruby:latest

RUN apt-get update -y && \
    apt-get install -y \
    lsof \
    build-essential \
    libpq-dev \
    nodejs \
    ca-certificates \
    openssl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /authentication/ssl_certs && \
    openssl req -new -x509 -days 365 -nodes -out /ssl_certs/server.crt -keyout /ssl_certs/server.key -subj "/C=IT/ST=F/L=MyCity/O=MyOrg/OU=MyDept/CN=localhost"

RUN update-ca-certificates && gem install bundler && bundle install

COPY /ssl_certs/server.crt /usr/local/share/ca-certificates/
COPY srcs/trascendence/ /var/www/

WORKDIR /var/www/authentication

EXPOSE 8433

CMD ["bundle", "exec", "ruby", "server.rb"]
