FROM ruby:latest

RUN apt-get update -y && \
    apt-get install -y \
    lsof \
    build-essential \
    libpq-dev \
    nodejs \
    ca-certificates \
    openssl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN update-ca-certificates && gem install bundler && bundle install

COPY /ssl_certs/server.crt /usr/local/share/ca-certificates/
COPY srcs/trascendence/ /var/www/

WORKDIR /var/www/authentication

EXPOSE 443

CMD ["bundle", "exec", "ruby", "server.rb"]
