FROM ruby:latest

RUN apt-get update -y && \
    apt-get install -y \
    lsof \
    build-essential \
    libpq-dev \
    nodejs \
    ca-certificates \
    openssl && \  
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /ssl_certs && \
    openssl req -new -x509 -days 365 -nodes -out /ssl_certs/server.crt -keyout /ssl_certs/server.key -subj "/C=IT/ST=F/L=MyCity/O=MyOrg/OU=MyDept/CN=localhost"

COPY /ssl_certs/server.crt /usr/local/share/ca-certificates/

RUN update-ca-certificates

RUN gem install bundler

WORKDIR /var/www

COPY srcs/trascendence/authentication /var/www/authentication

WORKDIR /var/www/authentication

RUN bundle install

COPY srcs/trascendence/ /var/www/

EXPOSE 8433

CMD ["bundle", "exec", "ruby", "server.rb"]
